use Marriage_Database;

Create table `Parish` (
`Parish_ID` smallint auto_increment not null unique,
`Parish` varchar(60) not null,
primary key (`Parish_ID`)
);

insert into `Parish`(`Parish_ID`, `Parish`) values

(default, 'Blessed Sacrament, Bethany'),
(default, 'Cathedral of the Immaculate Conception, Kansas City'),
(default, 'Christ the King, Kansas City'),
(default, 'Church of the Annunciation, Kearney'),
(default, 'Church of the Good Shepherd, Smithville'),
(default, 'Church of the Holy Martyrs, Kansas City'),
(default, 'Church of the Santa Fe, Buckner'),
(default, 'Co-Cathedral of St. Joseph, St. Joseph'),
(default, 'Coronation of Our Lady, Grandview'),
(default, 'Guardian Angels, Kansas City'),
(default, 'Holy Cross, Kansas City'),
(default, 'Holy Family, Kansas City'),
(default, 'Holy Rosary, Clinton'),
(default, 'Holy Rosary, Kansas City'),
(default, 'Holy Spirit, Lee''s Summit'),
(default, 'Holy Trinity, Urich'),
(default, 'Holy Trinity, Weston'),
(default, 'Immaculate Conception, Lexington'),
(default, 'Immaculate Conception, Montrose'),
(default, 'Immaculate Conception, Richmond'),
(default, 'Immaculate Heart of Mary, Princeton'),
(default, 'Mary Immaculate, Gallatin '),
(default, 'Nativity of Blessed Virgin Mary, Independence'),
(default, 'Oratory of Old St. Patrick, Kansas City'),
(default, 'Our Lady of Good Counsel, Kansas City'),
(default, 'Our Lady of Guadalupe, St. Joseph'),
(default, 'Our Lady of Lourdes, Harrisonville'),
(default, 'Our Lady of Lourdes, Kansas City'),
(default, 'Our Lady of Peace, Kansas City'),
(default, 'Our Lady of Perpetual Help, Kansas City'),
(default, 'Our Lady of Sorrows, Kansas City'),
(default, 'Our Lady of the Presentation, Lee''s Summit'),
(default, 'Sacred Heart, Hamilton'),
(default, 'Sacred Heart, Norborne '),
(default, 'Sacred Heart, Warrensburg'),
(default, 'Sacred Heart-Guadalupe, Kansas City'),
(default, 'Seven Dolors, Hurlingen'),
(default, 'St. Aloysius, Maysville'),
(default, 'St. Andrew the Apostle, Kansas City'),
(default, 'St. Ann, Excelsior Springs'),
(default, 'St. Ann, Independence'),
(default, 'St. Ann, Plattsburg '),
(default, 'St. Anthony, Kansas City'),
(default, 'St. Bartholomew, Windsor'),
(default, 'St. Benedict, Burlington Junction'),
(default, 'St. Bernadette, Kansas City'),
(default, 'St. Bridget, Pleasant Hill'),
(default, 'St. Bridget, Rich Hill'),
(default, 'St. Catherine, Osceola'),
(default, 'St. Catherine of Siena, Kansas City'),
(default, 'St. Charles Borromeo, Kansas City'),
(default, 'St. Columba, Conception Junction '),
(default, 'St. Columban, Chillicothe'),
(default, 'St. Cyril, Sugar Creek'),
(default, 'St. Elizabeth, Kansas City'),
(default, 'St. Francis Xavier, Kansas City'),
(default, 'St. Francis Xavier, St. Joseph'),
(default, 'St. Gabriel Archangel, Kansas City'),
(default, 'St. George, Odessa'),
(default, 'St. Gregory Barbarigo, Maryville'),
(default, 'St. James, Kansas City'),
(default, 'St. James, Liberty'),
(default, 'St. James, St. Joseph'),
(default, 'St. John Francis Regis, Kansas City'),
(default, 'St. John LaLande, Blue Springs'),
(default, 'St. Joseph  the Worker, Independence'),
(default, 'St. Joseph, Easton'),
(default, 'St. Joseph, Parnell'),
(default, 'St. Joseph, Trenton'),
(default, 'St. Jude the Apostle, Oak Grove'),
(default, 'St. Louis, Kansas City'),
(default, 'St. Margaret  of Scotland, Lee''s Summit'),
(default, 'St. Mark, Independence'),
(default, 'St. Mary, Carrollton '),
(default, 'St. Mary, Higginsville'),
(default, 'St. Mary, Independence'),
(default, 'St. Mary, Nevada'),
(default, 'St. Mary, St. Joseph'),
(default, 'St. Matthew Apostle, Kansas City'),
(default, 'St. Monica, Kansas City'),
(default, 'St. Munchin, Cameron'),
(default, 'St. Patrick, Butler'),
(default, 'St. Patrick, Ford City'),
(default, 'St. Patrick, Forest City'),
(default, 'St. Patrick, Holden '),
(default, 'St. Patrick, Kansas City'),
(default, 'St. Patrick, St. Joseph'),
(default, 'St. Paul the Apostle, Tarkio'),
(default, 'St. Peter, Kansas City'),
(default, 'St. Peter, Stanberry'),
(default, 'St. Robert Bellarmine, Blue Springs '),
(default, 'St. Rose of Lima, Savannah'),
(default, 'St. Sabina, Belton'),
(default, 'St. Therese, Kansas City'),
(default, 'St. Therese Little Flower, Kansas City'),
(default, 'St. Thomas More, Kansas City'),
(default, 'Twelve Apostles Parish, Platte City'),
(default, 'Visitation, Kansas City');

